"""create_all_tables

Revision ID: 2415ad074288
Revises: 0643edb34404
Create Date: 2025-06-26 21:27:08.847165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2415ad074288'
down_revision: Union[str, None] = '0643edb34404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('google_calendar_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('is_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_id'), 'oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_table('syllabi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('instructor_name', sa.String(), nullable=True),
    sa.Column('instructor_email', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('meeting_days', sa.String(), nullable=True),
    sa.Column('meeting_time', sa.String(), nullable=True),
    sa.Column('meeting_location', sa.String(), nullable=True),
    sa.Column('first_class', sa.String(), nullable=True),
    sa.Column('last_class', sa.String(), nullable=True),
    sa.Column('midterm_dates', sa.String(), nullable=True),
    sa.Column('final_exam_date', sa.String(), nullable=True),
    sa.Column('grading_policy', sa.String(), nullable=True),
    sa.Column('schedule_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabi_id'), 'syllabi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabi_id'), table_name='syllabi')
    op.drop_table('syllabi')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_table('google_calendar_credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
