"""add_s3_file_key_column

Revision ID: 729e471f2b84
Revises: a9dc911f2861
Create Date: 2025-07-09 18:20:54.558943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729e471f2b84'
down_revision: Union[str, None] = 'a9dc911f2861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_google_calendar_credentials_user_id', table_name='google_calendar_credentials')
    op.add_column('syllabi', sa.Column('s3_file_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syllabi', 's3_file_key')
    op.create_index('idx_google_calendar_credentials_user_id', 'google_calendar_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###
