"""make_refresh_token_nullable

Revision ID: a9dc911f2861
Revises: 2415ad074288
Create Date: 2025-07-01 23:03:49.635773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9dc911f2861'
down_revision: Union[str, None] = '2415ad074288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_credentials', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_credentials', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
